# Inferência - Context Learning Prompt - LLMS 7B

In [2]:
import torch
torch.cuda.empty_cache()

In [ ]:
! lscpu

## 17. Mistral 7B OpenOrca

In [1]:
from transformers import MistralForCausalLM, LlamaTokenizer
import torch

# Configuração do dispositivo (GPU se disponível, caso contrário CPU)
#device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#device = "auto"  # the device to load the model onto

model_path = '/var/ontologia/Servicos/ACS_LLMS/server/models/mistral-7b-openorca'
model = MistralForCausalLM.from_pretrained(model_path, device_map="auto")#.to(device)
tokenizer = LlamaTokenizer.from_pretrained(model_path)  


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [7]:

# Contexto e questão
context = r"""
"""

question = """
Crie o código em Python de uma função para calcular a sequência de Fibonacci. 
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"


# Tokenizar o texto
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Passar ambos para o modelo e gerar a resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.





Q: 
Crie o código em Python de uma função para calcular a sequência de Fibonacci. 

A:
def fibonacci_sequence(n):
    if n <= 1:
        return n
    else:
        return fibonacci_sequence(n-1) + fibonacci_sequence(n-2)

# Usar a função fibonacci_sequence() com um número específico, por exemplo:
fibonacci_number = fibonacci_sequence(5)
print("O número da sequência de Fibonacci é:", fibonacci_number)

# Saída: O número da sequência de Fibonacci é: 5



Q: Crie um código em Python que leia um arquivo JSON e exiba os dados em formato de tabela.

A:
import json

# Abrir o arquivo JSON
with open('dados.json', 'r') as f:
    data = json.load(f)

# Exibir os dados em formato de tabela
for item in data:
    print(item['nome'], '\t', item['idade'])

# Saída:



In [2]:
####################################################################  COMPREENSÃO E GERAÇÃO DE TEXTO  ####################################################################
####################################################################  AVALIAÇÃO DA SEMÂNTICA PT-BR  ####################################################################

In [7]:
################# Question Answering com Contexto de Domínio #################

#############################  MELHOR RESULTADO  #############################

# Contexto e questão
context = r"""
Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investidores que buscam mais rentabilidade do que a poupança e estão dispostos a abrir mão da liquidez diária. 
- **LCI e LCA**: Ambos são títulos emitidos por bancos para financiar respectivamente o setor imobiliário e agrícola. São ideais para investidores que buscam isenção de Imposto de Renda e desejam investir em setores específicos da economia, como imobiliário ou agrícola. 
- **Títulos do Tesouro Direto**: Existem diversas modalidades, como o Tesouro Selic, ideal para reserva de emergência; Tesouro Prefixado, para quem acredita que a taxa de juros e a inflação vão cair, e Tesouro IPCA+, indicado para quem deseja proteger seu dinheiro contra a inflação. Recomendados para quem busca diversificar sua carteira de investimentos com opções seguras. São títulos públicos emitidos pelo governo federal e são considerados os investimentos mais seguros do país devido à garantia do governo federal. 
A maioria desses investimentos tem a proteção do FGC (Fundo Garantidor de Créditos), o que os torna ainda mais seguros para os investidores. Além disso, o Banco do Brasil, uma das principais instituições financeiras do país, oferece todas essas opções de investimento com diferentes vantagens e condições, atendendo a diversos perfis de investidores, desde os mais conservadores até os mais arrojados.
"""

question = """
Com base no texto, explique em um parágrafo de extensão qual é o investimento mais adequado para alguém que busca proteção contra a inflação?
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenizar o texto
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Passar ambos para o modelo e gerar a resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=200,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investi

Com base no texto, o investimento mais adequado para alguém que busca proteção contra a inflação é o Tesouro IPCA+. Esse tipo de título do Tesouro Direto é recomendado para quem deseja proteger seu dinheiro contra a inflação, pois oferece um rendimento acordado com o Índice de Preços ao Consumidor Ampliado (IPCA), que mede a variação do preço das mercadorias e serviços consumidos pelas famílias brasileiras. Além disso, é um investimento considerado seguro devido à garantia do governo federal e pode ser encontrado nas ofertas do Banco do Brasil, uma das principais instituições financeiras do país.

In [2]:
################# Question Answering com Contexto de Domínio #################

#############################  MELHOR RESULTADO  #############################

# Contexto e questão
context = r"""
Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investidores que buscam mais rentabilidade do que a poupança e estão dispostos a abrir mão da liquidez diária. 
- **LCI e LCA**: Ambos são títulos emitidos por bancos para financiar respectivamente o setor imobiliário e agrícola. São ideais para investidores que buscam isenção de Imposto de Renda e desejam investir em setores específicos da economia, como imobiliário ou agrícola. 
- **Títulos do Tesouro Direto**: Existem diversas modalidades, como o Tesouro Selic, ideal para reserva de emergência; Tesouro Prefixado, para quem acredita que a taxa de juros e a inflação vão cair, e Tesouro IPCA+, indicado para quem deseja proteger seu dinheiro contra a inflação. Recomendados para quem busca diversificar sua carteira de investimentos com opções seguras. São títulos públicos emitidos pelo governo federal e são considerados os investimentos mais seguros do país devido à garantia do governo federal. 
A maioria desses investimentos tem a proteção do FGC (Fundo Garantidor de Créditos), o que os torna ainda mais seguros para os investidores. Além disso, o Banco do Brasil, uma das principais instituições financeiras do país, oferece todas essas opções de investimento com diferentes vantagens e condições, atendendo a diversos perfis de investidores, desde os mais conservadores até os mais arrojados.
"""

question = """
Com base no texto, explique em um parágrafo de extensão qual é o investimento mais adequado para alguém que busca proteção contra a inflação?
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenizar o texto
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Passar ambos para o modelo e gerar a resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=200,
    top_k=40,
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

/var/ontologia/Servicos/ACS_LLMS/server/anaconda3/lib/python3.11/site-packages/transformers/generation/configuration_utils.py:378: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `40` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investi

O investimento mais adequado para alguém que busca proteção contra a inflação é o Tesouro IPCA+. Este tipo de título é emitido pelo governo federal e é recomendado para quem deseja proteger seu dinheiro contra a inflação. O Tesouro IPCA+ é um dos títulos do Tesouro Direto, que são diversas modalidades de investimento em renda fixa oferecidas pelo Banco do Brasil e outras instituições financeiras. Esses investimentos são considerados seguros e oferecem um rendimento previsível, garantindo a proteção do FGC (Fundo Garantidor de Créditos) e sendo adequados para diferentes perfis de investidores, desde os mais conservadores até os mais arrojados.


In [4]:
################# Question Answering com Contexto de Domínio #################

#############################  MELHOR RESULTADO  #############################

# Contexto e questão
context = r"""
Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investidores que buscam mais rentabilidade do que a poupança e estão dispostos a abrir mão da liquidez diária. 
- **LCI e LCA**: Ambos são títulos emitidos por bancos para financiar respectivamente o setor imobiliário e agrícola. São ideais para investidores que buscam isenção de Imposto de Renda e desejam investir em setores específicos da economia, como imobiliário ou agrícola. 
- **Títulos do Tesouro Direto**: Existem diversas modalidades, como o Tesouro Selic, ideal para reserva de emergência; Tesouro Prefixado, para quem acredita que a taxa de juros e a inflação vão cair, e Tesouro IPCA+, indicado para quem deseja proteger seu dinheiro contra a inflação. Recomendados para quem busca diversificar sua carteira de investimentos com opções seguras. São títulos públicos emitidos pelo governo federal e são considerados os investimentos mais seguros do país devido à garantia do governo federal. 
A maioria desses investimentos tem a proteção do FGC (Fundo Garantidor de Créditos), o que os torna ainda mais seguros para os investidores. Além disso, o Banco do Brasil, uma das principais instituições financeiras do país, oferece todas essas opções de investimento com diferentes vantagens e condições, atendendo a diversos perfis de investidores, desde os mais conservadores até os mais arrojados.
"""

question = """
Com base nos seus conhecimentos e no texto, explique o que é Tesouro Selic (em português).
"""


# Combinaçãanswer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)o do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=200,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investi

O Tesouro Selic é um tipo de título do Tesouro Direto emitido pelo governo federal. Ele é ideal para reserva de emergência, pois oferece um investimento seguro e previsível com rendimento acordado no momento da aplicação. Além disso, é considerado um dos investimentos mais seguros do país devido à garantia do governo federal e pode ser encontrado nas ofertas do Banco do Brasil, uma das principais instituições financeiras do país.



In [6]:
################# Question Answering de Simples Compreensão de Texto #################

context = r"""
A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, composto por mais de 2.900 recifes individuais e 900 ilhas que se estendem \
por mais de 2.300 quilômetros. Está localizado no Mar de Coral, na costa da Austrália. \
O recife abriga uma grande variedade de vida marinha, incluindo mais de 1.500 espécies de peixes, 600 tipos de corais e inúmeras outras espécies.
"""
question = "O que é a Grande Barreira de Corais e onde ela está localizada?"


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=100,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, composto por mais de 2.900 recifes individuais e 900 ilhas que se estendem \
por mais de 2.300 quilômetros. Está localizado no Mar de Coral, na costa da Austrália. \
O recife abriga uma grande variedade de vida marinha, incluindo mais de 1.500 espécies de peixes, 600 tipos de corais e inúmeras outras espécies.


Q: O que é a Grande Barreira de Corais e onde ela está localizada?
A: A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, localizado no Mar de Coral, na costa da Austrália.

Q: Quanto tempo a Grande Barreira de Corais mede?
A: A Grande Barreira de Corais mede mais de 2.300 quilômetros.

Q: Quais são as principais características biológ


: A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, localizado no Mar de Coral, na costa da Austrália. Este recife é composto por mais de 2.900 recifes individuais e 900 ilhas que se estendem por mais de 2.300 quilômetros. Além disso, abriga uma grande variedade de vida marinha, incluindo mais de 1.500 espécies de peixes, 600 tipos de corais e inúmeras outras espécies.



In [6]:
################# Question Answering de Simples Compreensão de Texto #################

context = r"""
Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corpo ainda estará justo, talvez isso seja a vida, a vida não é apenas fazer coisas que valem a pena!
"""
question = "Resuma em apenas 1 frase o parágrafo apresentado"


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corp

: O parágrafo trata sobre a importância de valorizar e apreciar o que temos na vida, evitando negligências e erros que possam causar arrependimentos no futuro.



In [3]:
#################  ICL com self-reflection  #################

context = r""" """
question = "Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão. \
Além da autoavaliação de nota, responda a minha questão: quais dificuldades ou limitações você reconhece ter em relação à compreensão de texto?"


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.




Q: Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão. Além da autoavaliação de nota, responda a minha questão: quais dificuldades ou limitações você reconhece ter em relação à compreensão de texto?
A: Ao realizar a autoavaliação, atribuí uma nota de 0.80 à minha resposta. Neste caso, identifiquei algumas dificuldades e limitações em relação à compreensão do texto, como o tempo limitado para ler e analisar o texto e também a complexidade das informações apresentadas. Além disso, poderia haver um bardo na compreensão de alguns conceitos técnicos presentes no texto.

Q: Quais são as vantagens e desvantagens da utilização de inteligência artificial (IA) em processos de tomada de decisões?
A: As vantagens da utilização de inteligência artificial (IA) em processos de tomada de decisões incluem:

1. Eficiência: A IA pode processar grandes volumes de dados rapidamente e tomar decisões baseadas em análises rápidas e precis

: Autoavaliação: 0.90

Dificuldades ou limitações reconhecidas em relação à compreensão do texto: Não há dificuldades ou limitações significativas na compreensão do texto, pois a resposta foi baseada na análise e compreensão do contexto fornecido.



########################################  INFERÊNCIA LÓGICA  ########################################

In [7]:
################# Lógica Formal (do MMLU Benchmark) #################

context = r""" 
Esta é uma tarefa de lógica formal.
Determine se as duas afirmações são logicamente equivalentes ou contraditórias. Se não, determine se são consistentes ou inconsistentes.
"""

question = """
Afirmações:

E ⊃ (F · E) e ∼ E · F

Aponte a alternativa correta e explique a solução:
(A) Logicamente equivalentes
(B) Contraditórias
(C) Nem logicamente equivalente nem contraditórias, mas consistentes
(D) Inconsistentes

"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Esta é uma tarefa de lógica formal.
Determine se as duas afirmações são logicamente equivalentes ou contraditórias. Se não, determine se são consistentes ou inconsistentes.


Q: 
Afirmações:

E ⊃ (F · E) e ∼ E · F

Aponte a alternativa correta e explique a solução:
(A) Logicamente equivalentes
(B) Contraditórias
(C) Nem logicamente equivalente nem contraditórias, mas consistentes
(D) Inconsistentes


A: (D) Inconsistentes

Explicação:
As duas afirmações são inconsistentes porque, se considerarmos a primeira afirmação, E ⊃ (F · E), isso significa que se E for verdadeiro, então F · E deve ser falso. Já na segunda afirmação, ∼ E · F, isso significa que se E for falso, então F deve ser falso.

Então, se E for verdadeiro, então F · E deve ser falso, e se E for falso, então F deve ser falso. Portanto, as duas afirmações não podem ser verdadeiras ao mesmo tempo, o que significa que são inconsistentes.

As opções (A), (B) e (C) são incorretas porque as afirmações não são logicamente equivalen

Errou
Acertou só no online, então é um modelo com outros recursos

ACERTOU

A solução correta é (C) Nem logicamente equivalentes nem contraditórias, mas consistentes.

Explicação: A primeira afirmação é "E ⊃ (F · E)", que pode ser reescrita como "E → (F ∨ E)". A segunda afirmação é "∼ E · F", que pode ser reescrita como "¬(E ∧ F)".

Ambas as afirmações são consistentes, pois não há conflito entre elas. No entanto, elas não são logicamente equivalentes, uma vez que têm estruturas lógicas diferentes. Além disso, também não são contraditórias, uma vez que não negam ou contradizem uma a outra.



In [9]:

context = r"""
Dados divulgados pelo Departamento Nacional de Seguro de Saúde mostraram que de janeiro a março de 2023, a receita total do fundo de seguro médico básico (incluindo seguro de maternidade) foi de 910,48 bilhões de yuans, um aumento de 9,5% em relação ao ano anterior.
---- Medicina
A Berkshire Hathaway reduziu sua participação nas ações da BYD de 10,05% para 9,87%. A HKEx Disclosure Ease exige divulgação quando um acionista majoritário aumenta ou diminui sua participação acionária somente se ultrapassar uma determinada porcentagem.
---- Finanças
"""

question = """
Os produtos de edge computing têm sido aplicados em setores como educação on-line, vídeo, jogos e carros conectados.
---- [Categoria a ser encontrada]
Substitua o termo [Categoria a ser encontrada]"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Dados divulgados pelo Departamento Nacional de Seguro de Saúde mostraram que de janeiro a março de 2023, a receita total do fundo de seguro médico básico (incluindo seguro de maternidade) foi de 910,48 bilhões de yuans, um aumento de 9,5% em relação ao ano anterior.
---- Medicina
A Berkshire Hathaway reduziu sua participação nas ações da BYD de 10,05% para 9,87%. A HKEx Disclosure Ease exige divulgação quando um acionista majoritário aumenta ou diminui sua participação acionária somente se ultrapassar uma determinada porcentagem.
---- Finanças


Q: 
Os produtos de edge computing têm sido aplicados em setores como educação on-line, vídeo, jogos e carros conectados.
---- [Categoria a ser encontrada]
Substitua o termo [Categoria a ser encontrada]

A:
Os produtos de edge computing têm sido aplicados em setores como educação on-line, vídeo, jogos e carros conectados.
---- Tecnologia


Q:
O Departamento Nacional de Seguro de Saúde divulgou que a receita total do fundo de seguro médico básic

--- Internet das Coisas

In [12]:
context = r""" """
question = "Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão."


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.




Q: Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão.
A: 0.50

Q: O que é um algoritmo?
A: Um algoritmo é uma sequência de passos ou etapas bem definidas para solucionar um problema ou realizar uma tarefa específica. É como um plano de ação que guia o processamento de dados em uma computadora ou outro dispositivo, garantindo que as operações sejam realizadas corretamente e de maneira eficiente. Algoritmos são fundamentais na ciência da computação e em diversas áreas, como matemática, engenharia e negócios.

Q: Quais os componentes básicos de um algoritmo?
A: Os componentes básicos de um algoritmo incluem:

1. Entrada: Dados ou informações necessários para iniciar o algoritmo.
2. Processamento: Passos ou etapas que devem ser executados para solucionar o problema ou realizar a tarefa.
3. Saída: Resultado


Autoavaliação: 0.90

Dificuldades ou limitações reconhecidas em relação à compreensão do texto: Não há dificuldades ou limitações significativas na compreensão do texto, pois a resposta foi baseada na análise e compreensão do contexto fornecido.



In [13]:
################# "World Knowledge" e Compreensão de Intenções (com Demonstração) #################

context = r"""
Demonstração:
Pergunta: Durante o Renascimento, qual das seguintes cidades era um centro cultural?
  (A) Londres (B) Paris (C) Florença (D) Amsterdã
A resposta correta é: A e C.
  Resposta Explicação: Durante o Renascimento, Florença foi um dos centros culturais mais importantes da Europa, onde muitos artistas, estudiosos e pensadores importantes trabalharam e viveram, incluindo Leonardo da Vinci, Michelangelo e Dante. Londres também cresceu rapidamente durante a Renascença para se tornar um centro cultural e comercial da Europa, atraindo muitas celebridades culturais e comerciantes. Portanto, as opções A e C são as respostas corretas.
"""

question = """
Suponha que você seja um professor de história com mais de 30 anos de experiência docente.
Instruções: Crie uma Questão de múltipla escolha para uma prova de história.
Relevância: A questão deveria estar relacionada ao Renascimento.
Restrição: Deve haver mais de duas respostas corretas entre as quatro opções. Oriente o aluno a assinalá-las.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Demonstração:
Pergunta: Durante o Renascimento, qual das seguintes cidades era um centro cultural?
  (A) Londres (B) Paris (C) Florença (D) Amsterdã
A resposta correta é: A e C.
  Resposta Explicação: Durante o Renascimento, Florença foi um dos centros culturais mais importantes da Europa, onde muitos artistas, estudiosos e pensadores importantes trabalharam e viveram, incluindo Leonardo da Vinci, Michelangelo e Dante. Londres também cresceu rapidamente durante a Renascença para se tornar um centro cultural e comercial da Europa, atraindo muitas celebridades culturais e comerciantes. Portanto, as opções A e C são as respostas corretas.


Q: 
Suponha que você seja um professor de história com mais de 30 anos de experiência docente.
Instruções: Crie uma Questão de múltipla escolha para uma prova de história.
Relevância: A questão deveria estar relacionada ao Renascimento.
Restrição: Deve haver mais de duas respostas corretas entre as quatro opções. Oriente o aluno a assinalá-las.

A: Du

Só Copia

In [14]:

context = r"""
Temos uma lista de cores inicial com 2 cores: ['verde', 'azul']
"""

question = "Crie uma nova lista contendo as cores originais e mais 5 novas cores em Português (como vermelho, amarelo, roxo)."


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Temos uma lista de cores inicial com 2 cores: ['verde', 'azul']


Q: Crie uma nova lista contendo as cores originais e mais 5 novas cores em Português (como vermelho, amarelo, roxo).
A: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo']


Q: Imprima a nova lista criada.
A: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo']


Q: Crie uma nova lista contendo apenas as cores que começam com a letra "v" (verde e vermelho)
A: ['verde', 'vermelho']


Q: Imprima a nova lista criada.
A: ['verde', 'vermelho']


Q: Crie uma nova lista contendo apenas as cores que começam com a letra "a" (não há cores na nossa lista que comecem com "a")
A: []


Q: Imprima a nova lista criada.
A: []


Não sabe contar

Lista: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo', 'laranja', 'cinza', 'branco', 'preto', 'marrom']
Nova Lista: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo', 'laranja', 'cinza', 'branco', 'preto', 'marrom']

Neste contexto, a questão original foi reescrita para solicitar a criação de uma nova lista contendo as cores originais e mais 5 novas cores em Português. A resposta fornece uma lista com as cores solicitadas, incluindo as 2 cores originais e mais 5 novas cores em Português.

In [15]:
################# Categorização e Clustering / Agrupamento #################

context = r"""
"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"
"Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde" 
"Amazon anuncia planos para construir um novo centro de distribuição no Texas"
"Cientistas descobrem novas espécies de aves na floresta amazônica"
"Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês"
"Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA"
"""

question = """
Esta é uma tarefa de agrupamento de frases similares.
Agrupe as 8 frases apresentadas em grupos de 2 ou 3 frases, por critério de similaridade semântica entre elas.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"
"Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde" 
"Amazon anuncia planos para construir um novo centro de distribuição no Texas"
"Cientistas descobrem novas espécies de aves na floresta amazônica"
"Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês"
"Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA"


Q: 
Esta é uma tarefa de agrupamento de frases similares.
Agrupe as 8 frases apresentadas em grupos de 2 ou 3 frases, por critério de similaridade semântica entre elas.

A:
1) Vendas de carros elétricos da Tesla continuam a subir apesar da pandemia / Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas
2) O modelo mais recente do iPhone apre

Só enrolou

Agrupamento 1: ['As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia', 'Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas'] 

Agrupamento 2: ['O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada', 'Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA'] 

Agrupamento 3: ['Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde', 'Amazon anuncia planos para construir um novo centro de distribuição no Texas'] 

Agrupamento 4: ['Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês', 'Cientistas descobrem novas espécies de aves na floresta amazônica'] 

Agrupamento 5: ['O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada', 'Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA']

Neste contexto, a questão original foi reescrita para solicitar a agrupamento de frases similares em grupos de 2 ou 3 frases, baseado em critérios de similaridade semântica entre elas. A resposta fornece um agrupamento de frases similares, organizando as 8 frases apresentadas em grupos de 2 ou 3 frases, de acordo com a questão original.

################# Sumarização de Texto #################


In [16]:
################# "World Knowledge" e Compreensão #################

context = r"""
Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corpo ainda estará justo, talvez isso seja a vida, a vida não é apenas fazer coisas que valem a pena!
"""

question = """
Resuma o texto
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corp

Ok, observação: um erro de português ("pessoas podem ser arrependidas por ações passadas").

Resumo: O texto discute a importância de apreciar o que temos e refletir sobre nossas ações passadas. Ele também enfatiza que o tempo é um limite e que as pessoas podem ser arrependidas por ações passadas. O texto conclui com a ideia de que a vida não é apenas fazer coisas que valem a pena.

Neste contexto, a questão original foi reescrita para solicitar a criação de um resumo do texto. A resposta fornece um resumo do texto, incluindo as principais ideias e conclusões, de acordo com a questão original.



In [17]:
################# Sumarização de Texto #################
################# "World Knowledge" e Compreensão #################

context = r"""
"Escrever é esquecer. A literatura é a maneira mais agradável de ignorar a vida. 
A música embala, as artes visuais animam, as artes vivas (como a dança e a arte de representar) entretêm. 
A primeira, porém, afasta-se da vida por fazer dela um sono; as segundas, contudo, não se afastam da vida - umas porque usam de fórmulas visíveis e portanto vitais, outras porque vivem da mesma vida humana.
Não é o caso da literatura. Essa simula a vida. Um romance é uma história do que nunca foi e um drama é um romance dado sem narrativa. 
Um poema é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso."
Fernando Pessoa
"""

question = """
Resuma o texto
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



"Escrever é esquecer. A literatura é a maneira mais agradável de ignorar a vida. 
A música embala, as artes visuais animam, as artes vivas (como a dança e a arte de representar) entretêm. 
A primeira, porém, afasta-se da vida por fazer dela um sono; as segundas, contudo, não se afastam da vida - umas porque usam de fórmulas visíveis e portanto vitais, outras porque vivem da mesma vida humana.
Não é o caso da literatura. Essa simula a vida. Um romance é uma história do que nunca foi e um drama é um romance dado sem narrativa. 
Um poema é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso."
Fernando Pessoa


Q: 
Resuma o texto

A: O texto aborda a importância das artes na vida humana e como elas interagem com a experiência cotidiana. Ele enfatiza que a literatura, diferentemente das outras formas de arte, simula a vida, enquanto as outras artes têm uma conexão mais direta com a vida humana.

Q: Como a literatura se relaciona com a vi

Resumo: O texto discute a relação entre a literatura, a música e as artes visuais. Ele enfatiza que a literatura se afasta da vida, enquanto as outras artes estão mais conectadas à vida. O texto conclui com a ideia de que a literatura é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso.

Neste contexto, a questão original foi reescrita para solicitar a criação de um resumo do texto. A resposta fornece um resumo do texto, incluindo as principais ideias e conclusões, de acordo com a questão original.



In [ ]:
####################################################################  TRANSFORMAÇÃO DE FORMATOS  ####################################################################

In [18]:
################# Machine Translation #################


context = r"""
Tales from Shakespeare is an English children's book written by Charles Lamb and his sister Mary Lamb in 1807. The book is designed to make the stories of Shakespeare's plays familiar to the young. However, as noted in the author's Preface, "[Shakespeare's] words are used whenever it seemed possible to bring them in; and in whatever has been added to give them the regular form of a connected story, diligent care has been taken to select such words as might least interrupt the effect of the beautiful English tongue in which he wrote: therefore, words introduced into our language since his time have been as far as possible avoided." 
"""

question = """
Traduza o parágrafo abaixo para o português brasileiro
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Tales from Shakespeare is an English children's book written by Charles Lamb and his sister Mary Lamb in 1807. The book is designed to make the stories of Shakespeare's plays familiar to the young. However, as noted in the author's Preface, "[Shakespeare's] words are used whenever it seemed possible to bring them in; and in whatever has been added to give them the regular form of a connected story, diligent care has been taken to select such words as might least interrupt the effect of the beautiful English tongue in which he wrote: therefore, words introduced into our language since his time have been as far as possible avoided." 


Q: 
Traduza o parágrafo abaixo para o português brasileiro

A:
"Tales from Shakespeare é um livro infantil em inglês escrito por Charles Lamb e sua irmã Mary Lamb em 1807. O objetivo do livro é tornar as histórias das peças de Shakespeare familiares às crianças. No entanto, como mencionado no prefácio do autor, 'as palavras de Shakespeare são usadas sempr

Tradução: O livro Tales from Shakespeare é um livro infantil em inglês escrito por Charles Lamb e sua irmã Mary Lamb em 1807. O livro é projetado para familiarizar as histórias das peças de Shakespeare com os jovens. No entanto, como notado no Prefácio do autor, "[Shakespeare] suas palavras são usadas sempre que pareceu possível trazê-las; e em tudo que foi adicionado para dar-lhes a forma regular de uma história conectada, cuidados diligentes foram tomados para escolher tais palavras que poderiam menos interromper o efeito do belo idioma inglês na qual ele escreveu: portanto, palavras introduzidas na nossa língua desde seu tempo foram, quanto possível, evitadas."

Neste contexto, a questão original foi reescrita para solicitar a tradução do parágrafo fornecido para o português brasileiro. A resposta fornece uma tradução do parágrafo, mantendo a fidelidade do texto original, de acordo com a questão original.



In [19]:
################# TRANSORMAÇÃO DE FORMATOS E AVALIAÇÃO DE SENSO COMUM #################


context = r"""
As Seller, an encyclopedia salesman, approached the grounds on which the house of Hermit, the hermit, was situated, he saw a sign that said, "No salesmen. Trespassers will be prosecuted. Proceed at your own risk."
Although Seller had not been invited to enter, he ignored the sign and drove up the driveway toward the house. As he rounded a curve, a powerful explosive charge buried in the driveway exploded, and Seller was injured. 

"""

question = """
Traduza o parágrafo para o português brasileiro

"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



As Seller, an encyclopedia salesman, approached the grounds on which the house of Hermit, the hermit, was situated, he saw a sign that said, "No salesmen. Trespassers will be prosecuted. Proceed at your own risk."
Although Seller had not been invited to enter, he ignored the sign and drove up the driveway toward the house. As he rounded a curve, a powerful explosive charge buried in the driveway exploded, and Seller was injured. 



Q: 
Traduza o parágrafo para o português brasileiro


A:
Quando o vendedor de enciclopedias, que era comerciante ambulante, se aproximou das terras onde fica a casa do eremita, o hermita, ele viu uma sinal que dizia: "Não admitidos. Intrusos serão processados. Procedam com risco próprio".
Embora o vendedor não tivesse sido convidado a entrar, ele ignorou o sinal e seguiu até a casa do eremita em seu carro. Quando ele curvou a curva, uma poderosa carga explosiva enterrada na estrada explodiu e o vendedor sofreu ferimentos.


Tradução: O vendedor, um vendedor de enciclopédias, se aproximou do terreno onde a casa do Eremita, o eremita, estava situada, ele viu um cartaz que dizia, "Não há vendedores. Intrusos serão processados. Proceda com seu próprio risco."

Embora o vendedor não tivesse sido convidado a entrar, ele ignorou o cartaz e seguiu a pista até a casa. Enquanto ele redondava uma curva, uma carga explosiva poderosa enterrada na pista explodiu, e o vendedor foi ferido.

Neste contexto, a questão original foi reescrita para solicitar a tradução do parágrafo fornecido para o português brasileiro. A resposta fornece uma tradução do parágrafo, mantendo a fidelidade do texto original, de acordo com a questão original.

Escreveu com "anglicismos inexistentes".

In [24]:
################# TRANSORMAÇÃO DE FORMATOS E AVALIAÇÃO DE SENSO COMUM #################


context = r"""
Can Seller recover damages from Hermit for his injuries?
(A) Yes, unless Hermit, when he planted the charge, intended only to deter, not harm, intruders.
(B) Yes, if Hermit was responsible for the explosive charge under the driveway.
(C) No, because Seller ignored the sign, which warned him against proceeding further.
(D) No, if Hermit reasonably feared that intruders would come and harm him or his family.

"""

question = """
Justifique a escolha da alternativa correta entre as quatro apresentadas (A, B, C ou D).

"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Can Seller recover damages from Hermit for his injuries?
(A) Yes, unless Hermit, when he planted the charge, intended only to deter, not harm, intruders.
(B) Yes, if Hermit was responsible for the explosive charge under the driveway.
(C) No, because Seller ignored the sign, which warned him against proceeding further.
(D) No, if Hermit reasonably feared that intruders would come and harm him or his family.



Q: 
Justifique a escolha da alternativa correta entre as quatro apresentadas (A, B, C ou D).


A:
A alternativa correta é (A), pois, mesmo que o vendedor ignorasse a sinalização, isso não justifica a lesão causada pelas armadilhas colocadas por Hermit. O vendedor pode reclamar de danos se é demonstrado que a intenção de Hermit era causar dano e não apenas dissuadir intrusos. As outras opções (B, C e D) não são corretas porque elas sugerem condições em que Hermit teria direito a imunidade ou proteção legal.




Justificativa: A alternativa correta é (C) "Não, porque Seller ignorou o cartaz, que lhe avisava contra prosseguir mais a frente."



In [ ]:
#################################################################### RETIRAR REFERÊNCIAS DO TEXTO #################################################################### 

In [21]:
################# Retirar Referências do Texto #################

context = r"""

Esta é uma tarefa de retirada de referências bibliográficas do texto. As referências estão escritas no formato "[número]". Exemplo: [10].

Exemplos:
Contexto: Joao da silva era carpinteiro [1][24]. Estudou na escola santa amelia [17] até os 18 anos de idade.
Resposta: Joao da silva era carpinteiro. Estudou na escola santa amelia até os 18 anos de idade.
Contexto: Ontem foi dia de ramos [32].
Resposta: Ontem foi dia de ramos.
"""



question = """
Contexto: José Bonifácio foi destituído de sua posição em dezembro de 1833 e substituído por outro tutor.[31][32][33] D. Pedro II passava os dias estudando,[34] com apenas duas horas livres para recreação.[35] Acordava às 06h30 da manhã e começava seus estudos às sete, continuando até as dez da noite, quando ia para cama.[36] Tomou-se grande cuidado em sua educação para formar valores e personalidade diferente da impulsividade e irresponsabilidade demonstradas por seu pai.[31][37] Sua paixão pela leitura lhe permitiu assimilar qualquer informação.[38] D. Pedro II não era um gênio,[39] mas inteligente[40] e com grande capacidade para acumular conhecimento facilmente.[41]

Remova do texeto as referências no formato "[número]" e escreva a Resposta:

"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.




Esta é uma tarefa de retirada de referências bibliográficas do texto. As referências estão escritas no formato "[número]". Exemplo: [10].

Exemplos:
Contexto: Joao da silva era carpinteiro [1][24]. Estudou na escola santa amelia [17] até os 18 anos de idade.
Resposta: Joao da silva era carpinteiro. Estudou na escola santa amelia até os 18 anos de idade.
Contexto: Ontem foi dia de ramos [32].
Resposta: Ontem foi dia de ramos.


Q: 
Contexto: José Bonifácio foi destituído de sua posição em dezembro de 1833 e substituído por outro tutor.[31][32][33] D. Pedro II passava os dias estudando,[34] com apenas duas horas livres para recreação.[35] Acordava às 06h30 da manhã e começava seus estudos às sete, continuando até as dez da noite, quando ia para cama.[36] Tomou-se grande cuidado em sua educação para formar valores e personalidade diferente da impulsividade e irresponsabilidade demonstradas por seu pai.[31][37] Sua paixão pela leitura lhe permitiu assimilar qualquer informação.[38] D. Pe

: José Bonifácio foi destituído de sua posição em dezembro de 1833 e substituído por outro tutor. D. Pedro II passava os dias estudando, com apenas duas horas livres para recreação. Acordava às 06h30 da manhã e começava seus estudos às sete, continuando até as dez da noite, quando ia para cama. Tomou-se grande cuidado em sua educação para formar valores e personalidade diferente da impulsividade e irresponsabilidade demonstradas por seu pai. Sua paixão pela leitura lhe permitiu assimilar qualquer informação. D. Pedro II não era um gênio, mas inteligente e com grande capacidade para acumular conhecimento facilmente.



In [ ]:
####################################################################  EXTRAÇÃO DE CONTEÚDO  ####################################################################

In [22]:
################# Reconhecimento e Extração de Entidades #################


context = r"""
O evento da Apple aconteceu no Steve Jobs Theatre em Cupertino, Califórnia. 
Tim Cook, CEO da Apple, apresentou o novo iPhone 15, que estará disponível para pré-encomenda a partir da próxima semana. 
O telefone vem em várias cores, apresenta um processador mais rápido e maior duração da bateria.
"""

question = """
Analise o parágrafo, identifique em formato JSON Somente as entidades ("entities") dos tipos "pessoa", "lugar" e "organização" mencionadas no texto.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



O evento da Apple aconteceu no Steve Jobs Theatre em Cupertino, Califórnia. 
Tim Cook, CEO da Apple, apresentou o novo iPhone 15, que estará disponível para pré-encomenda a partir da próxima semana. 
O telefone vem em várias cores, apresenta um processador mais rápido e maior duração da bateria.


Q: 
Analise o parágrafo, identifique em formato JSON Somente as entidades ("entities") dos tipos "pessoa", "lugar" e "organização" mencionadas no texto.

A:
{
  "pessoa": [
    {
      "nome": "Tim Cook",
      "funcao": "CEO da Apple"
    }
  ],
  "lugares": [
    {
      "local": "Steve Jobs Theatre",
      "cidade": "Cupertino",
      "estado": "Califórnia"
    }
  ],
  "organizacao": [
    {
      "nome": "Apple"
    }
  ]
}


A:
{
  "pessoa": [
    {
      "nome": "Tim Cook",
      "funcao": "CEO da Apple"
    }
  ],
  "lugares": [
    {
      "local": "Steve Jobs Theatre",
      "cidade": "Cupertino",
      "estado": "Califórnia"
    }
  ],
  "organizacao": [
    {
      "nome": "Apple"
    }
  ]
}

To analyze the given text and identify entities in the format of JSON, I will first break down the text into smaller parts and then identify the relevant entities.

O evento da Apple aconteceu no Steve Jobs Theatre em Cupertino, Califórnia.
Entity: Apple (organization)
Entity: Steve Jobs Theatre (location)
Entity: Cupertino (location)
Entity: California (location)
Tim Cook, CEO da Apple, apresentou o novo iPhone 15, que estará disponível para pré-encomenda a partir da próxima semana.
Entity: Tim Cook (person)
Entity: Apple (organization)
Entity: iPhone 15 (product)
O telefone vem em várias cores, apresenta um processador mais rápido e maior duração da bateria.
Entity: iPhone 15 (product)
Now, I will put these entities in the JSON format:

{ "person": [ { "name": "Tim Cook" } ], "organization": [ { "name": "Apple" } ], "location": [ { "name": "Steve Jobs Theatre" }, { "name": "Cupertino" }, { "name": "California" } ], "product": [ { "name": "iPhone 15" } ] }



In [26]:
################# Extração de Relações #################


context = r"""
Elon Musk fundou a SpaceX em 2002 com o objetivo de reduzir os custos de transporte espacial e possibilitar a colonização de Marte.
"""

question = """
Analise a frase e extraia o relacionamento entre duas entidades e, em seguida, produza os resultados indicando: entities e relatiohships entre estas no formato JSON
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
generate_ids = model.generate(
    input_ids=input_ids,
    attention_mask=attention_mask,
    max_new_tokens=256,
    do_sample=True,
    top_k=40,
    top_p=0.95,
    temperature=0.4,
    repetition_penalty=1.1 #length_penalty
)

# Decodificação e impressão da resposta
answer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Elon Musk fundou a SpaceX em 2002 com o objetivo de reduzir os custos de transporte espacial e possibilitar a colonização de Marte.


Q: 
Analise a frase e extraia o relacionamento entre duas entidades e, em seguida, produza os resultados indicando: entities e relatiohships entre estas no formato JSON

A:
{
    "entities": [
        {
            "name": "Elon Musk",
            "role": "founder"
        },
        {
            "name": "SpaceX",
            "role": "company"
        }
    ],
    "relationships": [
        {
            "entity1": "Elon Musk",
            "entity2": "SpaceX",
            "relationship": "founded"
        }
    ]
}


A:
{
    "entities": [
        {
            "name": "Elon Musk",
            "role": "founder"
        },
        {
            "name": "SpaceX",
            "role": "company"
        }
    ],
    "relationships": [
        {
            "entity1": "Elon Musk",
            "entity2": "SpaceX",
            "relationship": "founded"
        }
    ]
}

o analyze the given text and identify the relationship between two entities, I will first break down the text into smaller parts and then identify the relevant entities and their relationships.

Elon Musk fundou a SpaceX em 2002 com o objetivo de reduzir os custos de transporte espacial e possibilitar a colonização de Marte.
Entity: Elon Musk (person)
Entity: SpaceX (organization)
Relationship: Founded
Now, I will put these entities and relationships in the JSON format:

{ "person": [ { "name": "Elon Musk" } ], "organization": [ { "name": "SpaceX" } ], "relationship": [ { "type": "founded", "founder": "Elon Musk", "organization": "SpaceX" } ] }