## 18. OpenChat v3.5 7B

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM, LlamaForCausalLM, MistralForCausalLM, LlamaTokenizerFast
import torch

# Configuração do dispositivo (GPU se disponível, caso contrário CPU)
model_path = '/var/ontologia/Servicos/ACS_LLMS/server/models/openchat_3.5'

model = MistralForCausalLM.from_pretrained(model_path, device_map="auto")
tokenizer = LlamaTokenizerFast.from_pretrained(model_path) 


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [3]:

# Contexto e questão
context = r"""
"""

question = """
Crie o código em Python de uma função para calcular a sequência de Fibonacci. 
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"


# Tokenizar o texto
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.





Q: 
Crie o código em Python de uma função para calcular a sequência de Fibonacci. 

A:


```python
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(10))
```



















































































































































































In [49]:
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)

fibonacci(2)

1

In [ ]:
####################################################################  COMPREENSÃO E GERAÇÃO DE TEXTO  ####################################################################
####################################################################  AVALIAÇÃO DA SEMÂNTICA PT-BR  ####################################################################

In [13]:
################# Question Answering com Contexto de Domínio #################

#############################  MELHOR RESULTADO  #############################

# Contexto e questão
context = r"""
Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investidores que buscam mais rentabilidade do que a poupança e estão dispostos a abrir mão da liquidez diária. 
- **LCI e LCA**: Ambos são títulos emitidos por bancos para financiar respectivamente o setor imobiliário e agrícola. São ideais para investidores que buscam isenção de Imposto de Renda e desejam investir em setores específicos da economia, como imobiliário ou agrícola. 
- **Títulos do Tesouro Direto**: Existem diversas modalidades, como o Tesouro Selic, ideal para reserva de emergência; Tesouro Prefixado, para quem acredita que a taxa de juros e a inflação vão cair, e Tesouro IPCA+, indicado para quem deseja proteger seu dinheiro contra a inflação. Recomendados para quem busca diversificar sua carteira de investimentos com opções seguras. São títulos públicos emitidos pelo governo federal e são considerados os investimentos mais seguros do país devido à garantia do governo federal. 
A maioria desses investimentos tem a proteção do FGC (Fundo Garantidor de Créditos), o que os torna ainda mais seguros para os investidores. Além disso, o Banco do Brasil, uma das principais instituições financeiras do país, oferece todas essas opções de investimento com diferentes vantagens e condições, atendendo a diversos perfis de investidores, desde os mais conservadores até os mais arrojados.
"""

question = """
Com base no texto, explique em um parágrafo de extensão qual é o investimento mais adequado para alguém que busca proteção contra a inflação?
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenizar o texto
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=160,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investi

Com base no texto, o investimento mais adequado para alguém que busca proteção contra a inflação é o Tesouro IPCA+. Esse tipo de título do Tesouro Direto é recomendado para quem deseja proteger seu dinheiro contra a inflação, pois oferece um rendimento acordado com o Índice de Preços ao Consumidor Ampliado (IPCA), que mede a variação do preço das mercadorias e serviços consumidos pelas famílias brasileiras. Além disso, é um investimento considerado seguro devido à garantia do governo federal e pode ser encontrado nas ofertas do Banco do Brasil, uma das principais instituições financeiras do país.

O investimento mais adequado para alguém que busca proteção contra a inflação é o Tesouro IPCA+. Este tipo de título é emitido pelo governo federal e é recomendado para quem deseja proteger seu dinheiro contra a inflação. O Tesouro IPCA+ é um dos títulos do Tesouro Direto, que são diversas modalidades de investimento em renda fixa oferecidas pelo Banco do Brasil e outras instituições financeiras. Esses investimentos são considerados seguros e oferecem um rendimento previsível, garantindo a proteção do FGC (Fundo Garantidor de Créditos) e sendo adequados para diferentes perfis de investidores, desde os mais conservadores até os mais arrojados.


In [15]:
################# Question Answering com Contexto de Domínio #################

#############################  MELHOR RESULTADO  #############################

# Contexto e questão
context = r"""
Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investidores que buscam mais rentabilidade do que a poupança e estão dispostos a abrir mão da liquidez diária. 
- **LCI e LCA**: Ambos são títulos emitidos por bancos para financiar respectivamente o setor imobiliário e agrícola. São ideais para investidores que buscam isenção de Imposto de Renda e desejam investir em setores específicos da economia, como imobiliário ou agrícola. 
- **Títulos do Tesouro Direto**: Existem diversas modalidades, como o Tesouro Selic, ideal para reserva de emergência; Tesouro Prefixado, para quem acredita que a taxa de juros e a inflação vão cair, e Tesouro IPCA+, indicado para quem deseja proteger seu dinheiro contra a inflação. Recomendados para quem busca diversificar sua carteira de investimentos com opções seguras. São títulos públicos emitidos pelo governo federal e são considerados os investimentos mais seguros do país devido à garantia do governo federal. 
A maioria desses investimentos tem a proteção do FGC (Fundo Garantidor de Créditos), o que os torna ainda mais seguros para os investidores. Além disso, o Banco do Brasil, uma das principais instituições financeiras do país, oferece todas essas opções de investimento com diferentes vantagens e condições, atendendo a diversos perfis de investidores, desde os mais conservadores até os mais arrojados.
"""

question = """
Com base nos seus conhecimentos e no texto, explique o que é Tesouro Selic (em português).
"""


# Combinaçãanswer = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)o do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=160,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Os investimentos em renda fixa são considerados uma das opções mais seguras do mercado financeiro e são especialmente atraentes para investidores com perfil conservador. Esses investimentos são compostos principalmente por títulos de dívida, seja pública ou privada. No Brasil, muitos bancos, incluindo o Banco do Brasil, oferecem uma variedade de opções de investimento em renda fixa. Esses investimentos têm como característica principal o retorno previsível, e o rendimento, na maioria das vezes, é acordado no momento da aplicação.
- **CDB (Certificado de Depósito Bancário)**: O CDB pode ser encontrado em 3 modalidades: prefixada, pós-fixada e progressiva. Enquanto o CDB prefixado tem um rendimento acordado no ato da aplicação, o pós-fixado e o progressivo são atrelados ao CDI, com o último tendo sua taxa definida com base no tempo de permanência da aplicação. Apesar do prazo de vencimento, o CDB pós-fixado e o progressivo podem ser resgatados a qualquer momento. É adequado para investi

O Tesouro Selic é um tipo de título do Tesouro Direto emitido pelo governo federal. Ele é ideal para reserva de emergência, pois oferece um investimento seguro e previsível com rendimento acordado no momento da aplicação. Além disso, é considerado um dos investimentos mais seguros do país devido à garantia do governo federal e pode ser encontrado nas ofertas do Banco do Brasil, uma das principais instituições financeiras do país.



In [16]:
################# Question Answering de Simples Compreensão de Texto #################

context = r"""
A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, composto por mais de 2.900 recifes individuais e 900 ilhas que se estendem \
por mais de 2.300 quilômetros. Está localizado no Mar de Coral, na costa da Austrália. \
O recife abriga uma grande variedade de vida marinha, incluindo mais de 1.500 espécies de peixes, 600 tipos de corais e inúmeras outras espécies.
"""
question = "O que é a Grande Barreira de Corais e onde ela está localizada?"


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=160,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, composto por mais de 2.900 recifes individuais e 900 ilhas que se estendem \
por mais de 2.300 quilômetros. Está localizado no Mar de Coral, na costa da Austrália. \
O recife abriga uma grande variedade de vida marinha, incluindo mais de 1.500 espécies de peixes, 600 tipos de corais e inúmeras outras espécies.


Q: O que é a Grande Barreira de Corais e onde ela está localizada?
A: A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, localizado no Mar de Coral, na costa da Austrália.

Q: Como é a estrutura da Grande Barreira de Corais?
A: A Grande Barreira de Corais é composta por mais de 2.900 recifes individuais e 900 ilhas que se estendem por mais de 2.300 quilômetros.

Q: Qual é a importância da Grande Barreira de Corais em termos de biodiversidade?
A: A Grande Barreira de Corais abriga uma grande varied


: A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, localizado no Mar de Coral, na costa da Austrália. Este recife é composto por mais de 2.900 recifes individuais e 900 ilhas que se estendem por mais de 2.300 quilômetros. Além disso, abriga uma grande variedade de vida marinha, incluindo mais de 1.500 espécies de peixes, 600 tipos de corais e inúmeras outras espécies.



In [17]:
################# Question Answering de Simples Compreensão de Texto #################

context = r"""
Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corpo ainda estará justo, talvez isso seja a vida, a vida não é apenas fazer coisas que valem a pena!
"""
question = "Resuma em apenas 1 frase o parágrafo apresentado"


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=160,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corp

: O parágrafo trata sobre a importância de valorizar e apreciar o que temos na vida, evitando negligências e erros que possam causar arrependimentos no futuro.



In [19]:
#################  ICL com self-reflection  #################

context = r""" """
question = "Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão. \
Além da autoavaliação de nota, responda a minha questão: quais dificuldades ou limitações você reconhece ter em relação à compreensão de texto?"


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.




Q: Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão. Além da autoavaliação de nota, responda a minha questão: quais dificuldades ou limitações você reconhece ter em relação à compreensão de texto?
A: 0.80

As dificuldades que eu reconheço em relação à compreensão de texto são:

1. Compreensão de textos técnicos e especializados, que muitas vezes contêm terminologia e conceitos específicos a um ramo de atividade.
2. Compreensão de textos em que há muitas informações e detalhes, o que pode levar a uma confusão e dificuldade em identificar o principal tema ou objetivo do texto.
3. Compreensão de textos em que há muitas referências e citações a outras fontes, o que pode levar a uma dificuldade em entender o contexto e a relevância dessas referências.
4. Compreensão de textos em que há muitas palavras e frases idiomáticas, expressões e sarcasmos, o que pode levar a uma dificuldade em entender o significado literal das

: Autoavaliação: 0.90

Dificuldades ou limitações reconhecidas em relação à compreensão do texto: Não há dificuldades ou limitações significativas na compreensão do texto, pois a resposta foi baseada na análise e compreensão do contexto fornecido.



########################################  INFERÊNCIA LÓGICA  ########################################

In [5]:
################# Lógica Formal (do MMLU Benchmark) #################

context = r""" 
Esta é uma tarefa de lógica formal.
Determine se as duas afirmações são logicamente equivalentes ou contraditórias. Se não, determine se são consistentes ou inconsistentes.
"""

question = """
Afirmações:

E ⊃ (F · E) e ∼ E · F

Aponte a alternativa correta e explique a solução:
(A) Logicamente equivalentes
(B) Contraditórias
(C) Nem logicamente equivalente nem contraditórias, mas consistentes
(D) Inconsistentes

"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Esta é uma tarefa de lógica formal.
Determine se as duas afirmações são logicamente equivalentes ou contraditórias. Se não, determine se são consistentes ou inconsistentes.


Q: 
Afirmações:

E ⊃ (F · E) e ∼ E · F

Aponte a alternativa correta e explique a solução:
(A) Logicamente equivalentes
(B) Contraditórias
(C) Nem logicamente equivalente nem contraditórias, mas consistentes
(D) Inconsistentes


A:
(C) Nem logicamente equivalente nem contraditórias, mas consistentes

Explicação:

E ⊃ (F · E) significa que se E é verdadeira, então F · E é verdadeira.

```
E ⊃ (F · E)
```

```
E ⊃ F
E ⊃ E
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E ⊃ F
```

```
E 


Errou
Acertou só no online, então é um modelo com outros recursos

ACERTOU

A solução correta é (C) Nem logicamente equivalentes nem contraditórias, mas consistentes.

Explicação: A primeira afirmação é "E ⊃ (F · E)", que pode ser reescrita como "E → (F ∨ E)". A segunda afirmação é "∼ E · F", que pode ser reescrita como "¬(E ∧ F)".

Ambas as afirmações são consistentes, pois não há conflito entre elas. No entanto, elas não são logicamente equivalentes, uma vez que têm estruturas lógicas diferentes. Além disso, também não são contraditórias, uma vez que não negam ou contradizem uma a outra.



In [6]:

context = r"""
Dados divulgados pelo Departamento Nacional de Seguro de Saúde mostraram que de janeiro a março de 2023, a receita total do fundo de seguro médico básico (incluindo seguro de maternidade) foi de 910,48 bilhões de yuans, um aumento de 9,5% em relação ao ano anterior.
---- Medicina
A Berkshire Hathaway reduziu sua participação nas ações da BYD de 10,05% para 9,87%. A HKEx Disclosure Ease exige divulgação quando um acionista majoritário aumenta ou diminui sua participação acionária somente se ultrapassar uma determinada porcentagem.
---- Finanças
"""

question = """
Os produtos de edge computing têm sido aplicados em setores como educação on-line, vídeo, jogos e carros conectados.
---- [Categoria a ser encontrada]
Substitua o termo [Categoria a ser encontrada]"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Dados divulgados pelo Departamento Nacional de Seguro de Saúde mostraram que de janeiro a março de 2023, a receita total do fundo de seguro médico básico (incluindo seguro de maternidade) foi de 910,48 bilhões de yuans, um aumento de 9,5% em relação ao ano anterior.
---- Medicina
A Berkshire Hathaway reduziu sua participação nas ações da BYD de 10,05% para 9,87%. A HKEx Disclosure Ease exige divulgação quando um acionista majoritário aumenta ou diminui sua participação acionária somente se ultrapassar uma determinada porcentagem.
---- Finanças


Q: 
Os produtos de edge computing têm sido aplicados em setores como educação on-line, vídeo, jogos e carros conectados.
---- [Categoria a ser encontrada]
Substitua o termo [Categoria a ser encontrada]
A: 
Os produtos de edge computing têm sido aplicados em setores como educação on-line, vídeo, jogos e carros conectados.
---- Tecnologia


Q: 
A Berkshire Hathaway reduziu sua participação nas ações da BYD de 10,05% para 9,87%. A HKEx Disclosure

--- Tecnologia


Acertou

In [7]:
context = r""" """
question = "Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão."


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.




Q: Em seguida, faça uma autoavaliação e atribua-se uma nota de 0.00 a 1.00, avaliando a qualidade da sua resposta à questão.
A: 0.80

Q: O que é o que você mais gosta de fazer na sua vida?
A: Estudar e aprender novas coisas.

Q: Qual é o seu maior medo?
A: Não conseguir alcançar os meus objetivos.

Q: Qual é o seu maior sonho?
A: Ser um grande cientista e contribuir para o avanço da ciência.

Q: Qual é o seu maior desafio?
A: Encontrar o equilíbrio entre trabalho e vida pessoal.

Q: Qual é o seu maior sucesso?
A: Concluir minha graduação com sucesso.

Q: Qual é o seu maior fracasso?
A: Não conseguir manter uma relação duradoura.

Q: Qual é o seu maior desejo?
A: Ter uma família e criar um ambiente de amor e apoio.

Q: Qual é o seu maior medo?
A:


c



In [31]:
################# "World Knowledge" e Compreensão de Intenções (com Demonstração) #################

context = r"""
Demonstração:
Pergunta: Durante o Renascimento, qual das seguintes cidades era um centro cultural?
  (A) Londres (B) Paris (C) Florença (D) Amsterdã
A resposta correta é: A e C.
  Resposta Explicação: Durante o Renascimento, Florença foi um dos centros culturais mais importantes da Europa, onde muitos artistas, estudiosos e pensadores importantes trabalharam e viveram, incluindo Leonardo da Vinci, Michelangelo e Dante. Londres também cresceu rapidamente durante a Renascença para se tornar um centro cultural e comercial da Europa, atraindo muitas celebridades culturais e comerciantes. Portanto, as opções A e C são as respostas corretas.
"""

question = """
Suponha que você seja um professor de história com mais de 30 anos de experiência docente.
Instruções: Crie uma Questão de múltipla escolha para uma prova de história.
Relevância: A questão deveria estar relacionada ao Renascimento.
Restrição: Deve haver mais de duas respostas corretas entre as quatro opções. Oriente o aluno a assinalá-las.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=512,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Demonstração:
Pergunta: Durante o Renascimento, qual das seguintes cidades era um centro cultural?
  (A) Londres (B) Paris (C) Florença (D) Amsterdã
A resposta correta é: A e C.
  Resposta Explicação: Durante o Renascimento, Florença foi um dos centros culturais mais importantes da Europa, onde muitos artistas, estudiosos e pensadores importantes trabalharam e viveram, incluindo Leonardo da Vinci, Michelangelo e Dante. Londres também cresceu rapidamente durante a Renascença para se tornar um centro cultural e comercial da Europa, atraindo muitas celebridades culturais e comerciantes. Portanto, as opções A e C são as respostas corretas.


Q: 
Suponha que você seja um professor de história com mais de 30 anos de experiência docente.
Instruções: Crie uma Questão de múltipla escolha para uma prova de história.
Relevância: A questão deveria estar relacionada ao Renascimento.
Restrição: Deve haver mais de duas respostas corretas entre as quatro opções. Oriente o aluno a assinalá-las.

A: Du

Só Copia

In [21]:

context = r"""
Temos uma lista de cores inicial com 2 cores: ['verde', 'azul']
"""

question = "Crie uma nova lista contendo as cores originais e mais 5 novas cores em Português (como vermelho, amarelo, roxo)."


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Temos uma lista de cores inicial com 2 cores: ['verde', 'azul']


Q: Crie uma nova lista contendo as cores originais e mais 5 novas cores em Português (como vermelho, amarelo, roxo).
A: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo']


Q: Crie uma nova lista contendo as cores originais e mais 5 novas cores em Inglês (como red, yellow, purple).
A: ['green', 'blue', 'red', 'yellow', 'purple']


Q: Crie uma nova lista contendo apenas as cores originais.
A: ['verde', 'azul']


Q: Crie uma nova lista contendo apenas as cores adicionais.
A: ['vermelho', 'amarelo', 'roxo']


Q: Crie uma nova lista contendo apenas as cores adicionais em Inglês.
A: ['red', 'yellow', 'purple']


Q: Crie uma nova lista contendo apenas as cores originais em Inglês.
A: ['green', 'blue']


Q: Crie uma nova lista contendo as cores originais e as cores adicion


Não sabe contar

Lista: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo', 'laranja', 'cinza', 'branco', 'preto', 'marrom']
Nova Lista: ['verde', 'azul', 'vermelho', 'amarelo', 'roxo', 'laranja', 'cinza', 'branco', 'preto', 'marrom']

Neste contexto, a questão original foi reescrita para solicitar a criação de uma nova lista contendo as cores originais e mais 5 novas cores em Português. A resposta fornece uma lista com as cores solicitadas, incluindo as 2 cores originais e mais 5 novas cores em Português.

In [22]:
################# Categorização e Clustering / Agrupamento #################

context = r"""
"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"
"Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde" 
"Amazon anuncia planos para construir um novo centro de distribuição no Texas"
"Cientistas descobrem novas espécies de aves na floresta amazônica"
"Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês"
"Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA"
"""

question = """
Esta é uma tarefa de agrupamento de frases similares.
Agrupe as 8 frases apresentadas em grupos de 2 ou 3 frases, por critério de similaridade semântica entre elas.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Geração da resposta
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"
"Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde" 
"Amazon anuncia planos para construir um novo centro de distribuição no Texas"
"Cientistas descobrem novas espécies de aves na floresta amazônica"
"Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês"
"Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA"


Q: 
Esta é uma tarefa de agrupamento de frases similares.
Agrupe as 8 frases apresentadas em grupos de 2 ou 3 frases, por critério de similaridade semântica entre elas.

A:

Grupo 1:
"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"

Grupo 2:
"Novo estudo sugere que 

In [32]:
################# Categorização e Clustering / Agrupamento #################

context = r"""
"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"
"Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde" 
"Amazon anuncia planos para construir um novo centro de distribuição no Texas"
"Cientistas descobrem novas espécies de aves na floresta amazônica"
"Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês"
"Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA"
"""

question = """
Esta é uma tarefa de agrupamento de frases similares.
Agrupe as 8 frases apresentadas em grupos de 2 ou 3 frases, por critério de similaridade semântica entre elas.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

## Tokenizar o texto
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)

with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=512,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"
"Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde" 
"Amazon anuncia planos para construir um novo centro de distribuição no Texas"
"Cientistas descobrem novas espécies de aves na floresta amazônica"
"Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês"
"Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA"


Q: 
Esta é uma tarefa de agrupamento de frases similares.
Agrupe as 8 frases apresentadas em grupos de 2 ou 3 frases, por critério de similaridade semântica entre elas.

A:

Grupo 1:
"As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia"
"O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada"

Grupo 2:
"Novo estudo sugere que 

Só enrolou

Agrupamento 1: ['As vendas de carros elétricos da Tesla continuam a subir apesar da pandemia', 'Novo estudo sugere que o consumo de café pode diminuir o risco de doenças cardíacas'] 

Agrupamento 2: ['O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada', 'Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA'] 

Agrupamento 3: ['Casos de COVID-19 aumentam na Índia, sobrecarregando o sistema de saúde', 'Amazon anuncia planos para construir um novo centro de distribuição no Texas'] 

Agrupamento 4: ['Conferência global sobre mudanças climáticas será realizada em Paris no próximo mês', 'Cientistas descobrem novas espécies de aves na floresta amazônica'] 

Agrupamento 5: ['O modelo mais recente do iPhone apresenta uma tela maior e câmera aprimorada', 'Starbucks apresenta opções de leite vegetal em todas as lojas dos EUA']

Neste contexto, a questão original foi reescrita para solicitar a agrupamento de frases similares em grupos de 2 ou 3 frases, baseado em critérios de similaridade semântica entre elas. A resposta fornece um agrupamento de frases similares, organizando as 8 frases apresentadas em grupos de 2 ou 3 frases, de acordo com a questão original.

################# Sumarização de Texto #################


In [23]:
################# "World Knowledge" e Compreensão #################

context = r"""
Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corpo ainda estará justo, talvez isso seja a vida, a vida não é apenas fazer coisas que valem a pena!
"""

question = """
Resuma o texto
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Sabemos onde realmente está a pipa em nosso coração? Não conseguiremos isso de novo se perdermos isso na vida, talvez nos arrependamos e nos redimamos, mas tudo isso parece ser tarde demais. Sempre que a pipa é lançada no céu, não deveríamos nos perguntar se realmente valorizamos o que temos?
Cada um de nós fez algo na juventude que nos envergonhará no futuro. Essas coisas podem ser como uma sombra que o acompanha pelo resto da vida, de modo que você só consegue olhar para ela. Mas o tempo não vai mudar, os seus melhores esforços para compensar isso, como não é uma espécie de auto-ajuda? A beleza e a amizade da infância, por causa de uma negligência covarde e arruinada, se você tiver outra chance, você está disposto a se esforçar para recuperar aquele antigo eu?
Mas as pessoas são assim, vivem sempre dentro de um determinado limite de tempo, onde o mundo pode estar alguns anos depois nem elas conseguem entender, mas é isso que não conseguimos superar. Para você, mil vezes, todo o corp

Ok, observação: um erro de português ("pessoas podem ser arrependidas por ações passadas").

Resumo: O texto discute a importância de apreciar o que temos e refletir sobre nossas ações passadas. Ele também enfatiza que o tempo é um limite e que as pessoas podem ser arrependidas por ações passadas. O texto conclui com a ideia de que a vida não é apenas fazer coisas que valem a pena.

Neste contexto, a questão original foi reescrita para solicitar a criação de um resumo do texto. A resposta fornece um resumo do texto, incluindo as principais ideias e conclusões, de acordo com a questão original.



In [24]:
################# Sumarização de Texto #################
################# "World Knowledge" e Compreensão #################

context = r"""
"Escrever é esquecer. A literatura é a maneira mais agradável de ignorar a vida. 
A música embala, as artes visuais animam, as artes vivas (como a dança e a arte de representar) entretêm. 
A primeira, porém, afasta-se da vida por fazer dela um sono; as segundas, contudo, não se afastam da vida - umas porque usam de fórmulas visíveis e portanto vitais, outras porque vivem da mesma vida humana.
Não é o caso da literatura. Essa simula a vida. Um romance é uma história do que nunca foi e um drama é um romance dado sem narrativa. 
Um poema é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso."
Fernando Pessoa
"""

question = """
Resuma o texto
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



"Escrever é esquecer. A literatura é a maneira mais agradável de ignorar a vida. 
A música embala, as artes visuais animam, as artes vivas (como a dança e a arte de representar) entretêm. 
A primeira, porém, afasta-se da vida por fazer dela um sono; as segundas, contudo, não se afastam da vida - umas porque usam de fórmulas visíveis e portanto vitais, outras porque vivem da mesma vida humana.
Não é o caso da literatura. Essa simula a vida. Um romance é uma história do que nunca foi e um drama é um romance dado sem narrativa. 
Um poema é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso."
Fernando Pessoa


Q: 
Resuma o texto

A:
O texto fala sobre como a literatura é a maneira mais agradável de ignorar a vida. A literatura é uma forma de arte que se afasta da vida, enquanto as artes visuais e as artes vivas não se afastam da vida. A literatura simula a vida, enquanto as artes visuais e as artes vivas usam de fórmulas visíveis e vit

Resumo: O texto discute a relação entre a literatura, a música e as artes visuais. Ele enfatiza que a literatura se afasta da vida, enquanto as outras artes estão mais conectadas à vida. O texto conclui com a ideia de que a literatura é a expressão de ideias ou de sentimentos em linguagem que ninguém emprega, pois que ninguém fala em verso.

Neste contexto, a questão original foi reescrita para solicitar a criação de um resumo do texto. A resposta fornece um resumo do texto, incluindo as principais ideias e conclusões, de acordo com a questão original.



In [ ]:
####################################################################  TRANSFORMAÇÃO DE FORMATOS  ####################################################################

In [25]:
################# Machine Translation #################


context = r"""
Tales from Shakespeare is an English children's book written by Charles Lamb and his sister Mary Lamb in 1807. The book is designed to make the stories of Shakespeare's plays familiar to the young. However, as noted in the author's Preface, "[Shakespeare's] words are used whenever it seemed possible to bring them in; and in whatever has been added to give them the regular form of a connected story, diligent care has been taken to select such words as might least interrupt the effect of the beautiful English tongue in which he wrote: therefore, words introduced into our language since his time have been as far as possible avoided." 
"""

question = """
Traduza o parágrafo abaixo para o português brasileiro
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Tales from Shakespeare is an English children's book written by Charles Lamb and his sister Mary Lamb in 1807. The book is designed to make the stories of Shakespeare's plays familiar to the young. However, as noted in the author's Preface, "[Shakespeare's] words are used whenever it seemed possible to bring them in; and in whatever has been added to give them the regular form of a connected story, diligent care has been taken to select such words as might least interrupt the effect of the beautiful English tongue in which he wrote: therefore, words introduced into our language since his time have been as far as possible avoided." 


Q: 
Traduza o parágrafo abaixo para o português brasileiro

A: 
"Tales from Shakespeare é um livro infantil em inglês escrito por Charles Lamb e sua irmã Mary Lamb em 1807. O livro é projetado para tornar as histórias das peças de Shakespeare familiares às crianças. No entanto, como notado na Prefácio do autor, "[Shakespeare's] palavras são usadas sempre 

Tradução: O livro Tales from Shakespeare é um livro infantil em inglês escrito por Charles Lamb e sua irmã Mary Lamb em 1807. O livro é projetado para familiarizar as histórias das peças de Shakespeare com os jovens. No entanto, como notado no Prefácio do autor, "[Shakespeare] suas palavras são usadas sempre que pareceu possível trazê-las; e em tudo que foi adicionado para dar-lhes a forma regular de uma história conectada, cuidados diligentes foram tomados para escolher tais palavras que poderiam menos interromper o efeito do belo idioma inglês na qual ele escreveu: portanto, palavras introduzidas na nossa língua desde seu tempo foram, quanto possível, evitadas."

Neste contexto, a questão original foi reescrita para solicitar a tradução do parágrafo fornecido para o português brasileiro. A resposta fornece uma tradução do parágrafo, mantendo a fidelidade do texto original, de acordo com a questão original.



In [26]:
################# TRANSORMAÇÃO DE FORMATOS E AVALIAÇÃO DE SENSO COMUM #################


context = r"""
As Seller, an encyclopedia salesman, approached the grounds on which the house of Hermit, the hermit, was situated, he saw a sign that said, "No salesmen. Trespassers will be prosecuted. Proceed at your own risk."
Although Seller had not been invited to enter, he ignored the sign and drove up the driveway toward the house. As he rounded a curve, a powerful explosive charge buried in the driveway exploded, and Seller was injured. 

"""

question = """
Traduza o parágrafo para o português brasileiro

"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



As Seller, an encyclopedia salesman, approached the grounds on which the house of Hermit, the hermit, was situated, he saw a sign that said, "No salesmen. Trespassers will be prosecuted. Proceed at your own risk."
Although Seller had not been invited to enter, he ignored the sign and drove up the driveway toward the house. As he rounded a curve, a powerful explosive charge buried in the driveway exploded, and Seller was injured. 



Q: 
Traduza o parágrafo para o português brasileiro


A:
Como vendedor, um vendedor de enciclopédias, se aproximava dos terrenos em que a casa do ermitão, o ermitão, estava situada, ele viu um cartaz que dizia: "Não há vendedores. Infratores serão processados. Procedam à seu risco."
Embora Seller não tivesse sido convidado a entrar, ele ignorou o cartaz e dirigiu-se pela calçada em direção à casa. Enquanto ele redondava uma curva, uma carga explosiva poderosa enterrada na calçada explodiu e Seller foi ferido.

















































Tradução: O vendedor, um vendedor de enciclopédias, se aproximou do terreno onde a casa do Eremita, o eremita, estava situada, ele viu um cartaz que dizia, "Não há vendedores. Intrusos serão processados. Proceda com seu próprio risco."

Embora o vendedor não tivesse sido convidado a entrar, ele ignorou o cartaz e seguiu a pista até a casa. Enquanto ele redondava uma curva, uma carga explosiva poderosa enterrada na pista explodiu, e o vendedor foi ferido.

Neste contexto, a questão original foi reescrita para solicitar a tradução do parágrafo fornecido para o português brasileiro. A resposta fornece uma tradução do parágrafo, mantendo a fidelidade do texto original, de acordo com a questão original.

Escreveu com "anglicismos inexistentes".

In [27]:
################# TRANSORMAÇÃO DE FORMATOS E AVALIAÇÃO DE SENSO COMUM #################


context = r"""
Can Seller recover damages from Hermit for his injuries?
(A) Yes, unless Hermit, when he planted the charge, intended only to deter, not harm, intruders.
(B) Yes, if Hermit was responsible for the explosive charge under the driveway.
(C) No, because Seller ignored the sign, which warned him against proceeding further.
(D) No, if Hermit reasonably feared that intruders would come and harm him or his family.

"""

question = """
Justifique a escolha da alternativa correta entre as quatro apresentadas (A, B, C ou D).

"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Can Seller recover damages from Hermit for his injuries?
(A) Yes, unless Hermit, when he planted the charge, intended only to deter, not harm, intruders.
(B) Yes, if Hermit was responsible for the explosive charge under the driveway.
(C) No, because Seller ignored the sign, which warned him against proceeding further.
(D) No, if Hermit reasonably feared that intruders would come and harm him or his family.



Q: 
Justifique a escolha da alternativa correta entre as quatro apresentadas (A, B, C ou D).


A:
(D)






























































































































































































































































In [28]:
################# Retirar Referências do Texto #################

context = r"""

Esta é uma tarefa de retirada de referências bibliográficas do texto. As referências estão escritas no formato "[número]". Exemplo: [10].

Exemplos:
Contexto: Joao da silva era carpinteiro [1][24]. Estudou na escola santa amelia [17] até os 18 anos de idade.
Resposta: Joao da silva era carpinteiro. Estudou na escola santa amelia até os 18 anos de idade.
Contexto: Ontem foi dia de ramos [32].
Resposta: Ontem foi dia de ramos.
"""



question = """
Contexto: José Bonifácio foi destituído de sua posição em dezembro de 1833 e substituído por outro tutor.[31][32][33] D. Pedro II passava os dias estudando,[34] com apenas duas horas livres para recreação.[35] Acordava às 06h30 da manhã e começava seus estudos às sete, continuando até as dez da noite, quando ia para cama.[36] Tomou-se grande cuidado em sua educação para formar valores e personalidade diferente da impulsividade e irresponsabilidade demonstradas por seu pai.[31][37] Sua paixão pela leitura lhe permitiu assimilar qualquer informação.[38] D. Pedro II não era um gênio,[39] mas inteligente[40] e com grande capacidade para acumular conhecimento facilmente.[41]

Remova do texeto as referências no formato "[número]" e escreva a Resposta:

"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.




Esta é uma tarefa de retirada de referências bibliográficas do texto. As referências estão escritas no formato "[número]". Exemplo: [10].

Exemplos:
Contexto: Joao da silva era carpinteiro [1][24]. Estudou na escola santa amelia [17] até os 18 anos de idade.
Resposta: Joao da silva era carpinteiro. Estudou na escola santa amelia até os 18 anos de idade.
Contexto: Ontem foi dia de ramos [32].
Resposta: Ontem foi dia de ramos.


Q: 
Contexto: José Bonifácio foi destituído de sua posição em dezembro de 1833 e substituído por outro tutor.[31][32][33] D. Pedro II passava os dias estudando,[34] com apenas duas horas livres para recreação.[35] Acordava às 06h30 da manhã e começava seus estudos às sete, continuando até as dez da noite, quando ia para cama.[36] Tomou-se grande cuidado em sua educação para formar valores e personalidade diferente da impulsividade e irresponsabilidade demonstradas por seu pai.[31][37] Sua paixão pela leitura lhe permitiu assimilar qualquer informação.[38] D. Pe

A: 
José Bonifácio foi destituído de sua posição em dezembro de 1833 e substituído por outro tutor. D. Pedro II passava os dias estudando, com apenas duas horas livres para recreação. Acordava às 06h30 da manhã e começava seus estudos às sete, continuando até as dez da noite, quando ia para cama. Tomou-se grande cuidado em sua educação para formar valores e personalidade diferente da impulsividade e irresponsabilidade demonstradas por seu pai. Sua paixão pela leitura lhe permitiu assimilar qualquer informação. D. Pedro II não era um gênio, mas inteligente e com grande capacidade para acumular conhecimento facilmente.



In [ ]:
####################################################################  EXTRAÇÃO DE CONTEÚDO  ####################################################################

In [3]:
################# Reconhecimento e Extração de Informações Específicas #################

context = r"""
Texto de Referência:
O Brasil é o quinto maior país do mundo em território, com uma área total de 8.515.767 quilômetros quadrados. É também o quinto país mais populoso do mundo, \
com uma população estimada em cerca de 211 milhões de pessoas em 2021. \
O país é conhecido por sua diversidade cultural e natural, incluindo a floresta Amazônica, que é a maior floresta tropical do mundo.
Pergunta: Qual a dimensão do Brasil em área?
Resposta: 8.515.767 quilômetros quadrados.

"""
question = """
Texto de Referência:
O Brasil é o quinto maior país do mundo em território, com uma área total de 8.515.767 quilômetros quadrados. É também o quinto país mais populoso do mundo, com uma população estimada em cerca de 211 milhões de pessoas em 2021. O país é conhecido por sua diversidade cultural e natural, incluindo a floresta Amazônica, que é a maior floresta tropical do mundo.
Pergunta: Qual é a posição do Brasil em termos de tamanho de território e população, e qual é a principal característica natural mencionada no texto?
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)


Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Texto de Referência:
O Brasil é o quinto maior país do mundo em território, com uma área total de 8.515.767 quilômetros quadrados. É também o quinto país mais populoso do mundo, \
com uma população estimada em cerca de 211 milhões de pessoas em 2021. \
O país é conhecido por sua diversidade cultural e natural, incluindo a floresta Amazônica, que é a maior floresta tropical do mundo.
Pergunta: Qual a dimensão do Brasil em área?
Resposta: 8.515.767 quilômetros quadrados.



Q: 
Texto de Referência:
O Brasil é o quinto maior país do mundo em território, com uma área total de 8.515.767 quilômetros quadrados. É também o quinto país mais populoso do mundo, com uma população estimada em cerca de 211 milhões de pessoas em 2021. O país é conhecido por sua diversidade cultural e natural, incluindo a floresta Amazônica, que é a maior floresta tropical do mundo.
Pergunta: Qual é a posição do Brasil em termos de tamanho de território e população, e qual é a principal característica natural mencion

Perfeito.
O Brasil é o quinto maior país do mundo em território e o quinto país mais populoso. A principal característica natural mencionada no texto é a floresta Amazônica, a maior floresta tropical do mundo.

In [4]:
################# Classificação de Intenções #################

context = r"""
Olá
Passei algum tempo analisando sua documentação, mas não consegui descobrir como adicionar um novo cartão de crédito.
É um problema porque meu cartão atual irá expirar em breve e temo que isso cause uma interrupção no serviço.
Como posso atualizar meu cartão de crédito?
Desde já, obrigado,
João Baião
"""
question = """
Classifique as intenções presentes no texto.
"""


# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)


Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Olá
Passei algum tempo analisando sua documentação, mas não consegui descobrir como adicionar um novo cartão de crédito.
É um problema porque meu cartão atual irá expirar em breve e temo que isso cause uma interrupção no serviço.
Como posso atualizar meu cartão de crédito?
Desde já, obrigado,
Ansioso por saber sobre você,
John Doe


Q: 
Classifique as intenções presentes no texto.

A: 
1. Informar - 10%
2. Pedir informações - 90%


Q: 
Qual a intenção do texto?

A: 
Pedir informações


Q: 
Qual o assunto do texto?

A: 
Adicionar um novo cartão de crédito


Q: 
Qual o tema do texto?

A: 
Atualização de informações


Q: 
Qual o tipo de texto?

A: 
Texto formal


Q: 
Qual o tom do texto?

A: 
Amigável


Q: 
Qual o nível de formalidade do texto?

A: 
Médio


Q: 
Qual o tipo de texto?

A: 
Texto de correio eletrônico


Q: 
Qual o assunto do texto?

A: 
Atualização de informações


Q: 
Qual


A: 
1. Informar - 10%
2. Pedir informações - 90%

In [29]:
################# Reconhecimento e Extração de Entidades #################


context = r"""
O evento da Apple aconteceu no Steve Jobs Theatre em Cupertino, Califórnia. 
Tim Cook, CEO da Apple, apresentou o novo iPhone 15, que estará disponível para pré-encomenda a partir da próxima semana. 
O telefone vem em várias cores, apresenta um processador mais rápido e maior duração da bateria.
"""

question = """
Analise o parágrafo, identifique em formato JSON Somente as entidades ("entities") dos tipos "pessoa", "lugar" e "organização" mencionadas no texto.
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



O evento da Apple aconteceu no Steve Jobs Theatre em Cupertino, Califórnia. 
Tim Cook, CEO da Apple, apresentou o novo iPhone 15, que estará disponível para pré-encomenda a partir da próxima semana. 
O telefone vem em várias cores, apresenta um processador mais rápido e maior duração da bateria.


Q: 
Analise o parágrafo, identifique em formato JSON Somente as entidades ("entities") dos tipos "pessoa", "lugar" e "organização" mencionadas no texto.

A:
{
  "pessoa": [
    {
      "nome": "Tim Cook",
      "função": "CEO da Apple"
    }
  ],
  "lugar": [
    {
      "nome": "Steve Jobs Theatre",
      "localização": "Cupertino, Califórnia"
    }
  ],
  "organização": [
    {
      "nome": "Apple"
    }
  ]
}


Q: 
Qual é o novo recurso do iPhone 15?

A: 
O novo recurso do iPhone 15 é o processador mais rápido e maior duração da bateria.


Q: 
Qual é o preço do novo iPhone 15?

A: 
Não há informação sobre o preço do novo iPhone 15 no texto fornecido.


Q: 
Em que local o evento da Apple 

A:
{
  "pessoa": [
    {
      "nome": "Tim Cook",
      "função": "CEO da Apple"
    }
  ],
  "lugar": [
    {
      "nome": "Steve Jobs Theatre",
      "localização": "Cupertino, Califórnia"
    }
  ],
  "organização": [
    {
      "nome": "Apple"
    }
  ]
}

In [30]:
################# Extração de Relações #################


context = r"""
Elon Musk fundou a SpaceX em 2002 com o objetivo de reduzir os custos de transporte espacial e possibilitar a colonização de Marte.
"""

question = """
Analise a frase e extraia o relacionamento entre duas entidades e, em seguida, produza os resultados indicando: entities e relatiohships entre estas no formato JSON
"""

# Combinação do contexto e da questão para formar o prompt
prompt = context + "\n\nQ: " + question + "\nA:"

# Tokenização do prompt
tokens = tokenizer(prompt, return_tensors="pt")

# Extrair os tensores de input_ids e da attention_mask
input_ids = tokens["input_ids"]
input_ids = input_ids.to('cuda')
attention_mask = tokens["attention_mask"]

# Outputs - Passar ambos para o modelo e gerar a resposta (generate_ids = outputs)
with torch.no_grad():
    generate_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_new_tokens=256,
        #do_sample=True,
        #top_k=40,
    )

# Decodificação e impressão da resposta (answer = last_hidden_states)
last_hidden_states = tokenizer.decode(generate_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)
answer = last_hidden_states
print(answer)

Setting `pad_token_id` to `eos_token_id`:32000 for open-end generation.



Elon Musk fundou a SpaceX em 2002 com o objetivo de reduzir os custos de transporte espacial e possibilitar a colonização de Marte.


Q: 
Analise a frase e extraia o relacionamento entre duas entidades e, em seguida, produza os resultados indicando: entities e relatiohships entre estas no formato JSON

A:
{
  "entities": [
    {
      "entity": "Elon Musk",
      "type": "person"
    },
    {
      "entity": "SpaceX",
      "type": "organization"
    },
    {
      "entity": "2002",
      "type": "date"
    },
    {
      "entity": "transporte espacial",
      "type": "activity"
    },
    {
      "entity": "colonização de Marte",
      "type": "activity"
    }
  ],
  "relationships": [
    {
      "subject": "Elon Musk",
      "predicate": "founded",
      "object": "SpaceX"
    },
    {
      "subject": "SpaceX",
      "predicate": "has_goal",
      "object": "reduce costs of space transport"
    },
    {
      "subject": "SpaceX",
      "predicate": "has_goal",
      "object": "ena

A:
{
  "entities": [
    {
      "entity": "Elon Musk",
      "type": "person"
    },
    {
      "entity": "SpaceX",
      "type": "organization"
    },
    {
      "entity": "2002",
      "type": "date"
    },
    {
      "entity": "transporte espacial",
      "type": "activity"
    },
    {
      "entity": "colonização de Marte",
      "type": "activity"
    }
  ],
  "relationships": [
    {
      "subject": "Elon Musk",
      "predicate": "founded",
      "object": "SpaceX"
    },
    {
      "subject": "SpaceX",
      "predicate": "has_goal",
      "object": "reduce costs of space transport"
    },
    {
      "subject": "SpaceX",
      "predicate": "has_goal",
      "object": "enable Mars colonization
    }